server:
  host: localhost
  port: 7264

  connection-config:
    read-timeout: PT5S
    connect-timeout: PT2S

#  log:
#    level: TRACE



mp:
  openapi:
    web-context: /swagger
    ui:
      enabled: true
      web-context: /ui

envs:
  WAKAMITI_PORT: server.port
  WAKAMITI_HOST: server.host

#  datasource:
#    db-kind: h2
#    jdbc:
#      url: jdbc:h2:mem:default
#    username: sa



