server:
  host: 127.0.0.1
  port: 7264

  connection-config:
    read-timeout: PT5S
    connect-timeout: PT2S

  config:
    path: ${user.home}/.wakamiti/config
  system:
    path: ${user.home}/.wakamiti/system
  plugins:
    path: ${user.home}/.wakamiti/plugins

  log:
    path: ${server.system.path}/log
    level: INFO

  auth:
    origin: waka.cli

mp:
  openapi:
    web-context: /swagger
    ui:
      enabled: true
      web-context: /ui

envs:
  WAKAMITI_PORT: server.port
  WAKAMITI_HOST: server.host

#  datasource:
#    db-kind: h2
#    jdbc:
#      url: jdbc:h2:mem:default
#    username: sa



