name: Deploy Snapshot
on:
  push:
    branches: [develop]
    paths:
      - 'src/**'
      - 'go.mod'
      - 'pom.xml'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
jobs:
  config_maven:
    name: Maven Configuration
    uses: wakamiti/wakamiti-github-actions/.github/workflows/maven.yml@main
    secrets: inherit
  validate_code:
    name: Validate Code
    uses: wakamiti/wakamiti-github-actions/.github/workflows/validate_code.yml@main
    needs: config_maven
    with:
      analyze: false
    secrets: inherit
  build:
    name: Deploy
    uses: wakamiti/wakamiti-github-actions/.github/workflows/snapshot.yml@main
    needs: [config_maven, validate_code]
    secrets: inherit
